server:
  port: 8082
spring:
  kafka:
    template:
      default-topic: coffee-orders
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    properties:
      schema.registry.url : http://localhost:8081