server:
  port: 8083
spring:
  kafka:
    template:
      default-topic: coffee-orders
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      group-id: coffee-orders-listener-group
    properties:
      schema.registry.url : http://localhost:8081